# RNN Cell
![G16Wwy](https://gitee.com/pxqp9W/testmarkdown/raw/master/imgs/2020/07/G16Wwy.png)
![ZND8NU](https://gitee.com/pxqp9W/testmarkdown/raw/master/imgs/2020/07/ZND8NU.png)
- [一文搞懂RNN（循环神经网络）基础篇 - 知乎](https://zhuanlan.zhihu.com/p/30844905)
- [一文看懂循环神经网络RNN（2种优化算法+5个实际应用）](https://easyai.tech/ai-definition/rnn/)

In [13]:
import torch

In [14]:
# Parameters
batch_size = 1
seq_len = 3
input_size = 4 
hidden_size = 2

In [15]:
# 可以直接调用PyTorch中的RNN Cell函数
cell = torch.nn.RNNCell(input_size=input_size, hidden_size=hidden_size)
# (seq, batch, features)
dataset = torch.randn(seq_len, batch_size, input_size) # 随机产生一组输入数据
hidden = torch.zeros(batch_size, hidden_size)  # h0初始化为全零

In [16]:
# RNN的循环过程
for idx, input in enumerate(dataset):
    print('=' * 20, idx, '=' * 20) 
    print('Input size: ', input.shape) 
    
    hidden = cell(input, hidden) # update hidden
    
    print('outputs size: ', hidden.shape) 
    print(hidden)

==================== 0 ====================
Input size:  torch.Size([1, 4])
outputs size:  torch.Size([1, 2])
tensor([[0.8024, 0.6569]], grad_fn=<TanhBackward>)
==================== 1 ====================
Input size:  torch.Size([1, 4])
outputs size:  torch.Size([1, 2])
tensor([[-0.5689,  0.0635]], grad_fn=<TanhBackward>)
==================== 2 ====================
Input size:  torch.Size([1, 4])
outputs size:  torch.Size([1, 2])
tensor([[0.2783, 0.1212]], grad_fn=<TanhBackward>)
