In [1]:
import torch 

In [2]:
in_channels, out_channels= 5, 10 
width, height = 100, 100 
kernel_size = 3 
batch_size = 1

input = torch.randn(batch_size,in_channels, width, height)
# torch.randn(*sizes, out=None):返回一个张量，包含了从标准正态分布(均值为0，方差为 1，即高斯白噪声)中抽取一组随机数，形状由可变参数sizes定义。 参数:
conv_layer = torch.nn.Conv2d(in_channels,out_channels, kernel_size=kernel_size)
output = conv_layer(input)

print(input.shape) 
print(output.shape)
print(conv_layer.weight.shape) # (m:output chanels, n:input chanels, kernel_width, kernel_height)

torch.Size([1, 5, 100, 100])
torch.Size([1, 10, 98, 98])
torch.Size([10, 5, 3, 3])


![5ceDgj](https://gitee.com/pxqp9W/testmarkdown/raw/master/imgs/2020/07/5ceDgj.png)

## Padding：边缘填充
![9vQgMx](https://gitee.com/pxqp9W/testmarkdown/raw/master/imgs/2020/07/9vQgMx.png)

In [3]:
input = [3,4,6,5,7, 2,4,6,8,2, 1,6,7,8,4, 9,7,4,6,2, 3,7,5,4,1]
input = torch.Tensor(input).view(1, 1, 5, 5) # input -> (B,C,W,H)形状的tensor
conv_layer = torch.nn.Conv2d(1, 1, kernel_size=3, padding=1, bias=False)
#  # (m:output chanels, n:input chanels, kernel_width, kernel_height)
kernel = torch.Tensor([1,2,3,4,5,6,7,8,9]).view(1, 1, 3, 3)  # -> (output Channel, input Channel, weight, height)
conv_layer.weight.data = kernel.data # 将kernel作为卷积层的权重
output = conv_layer(input) 
print(output)

tensor([[[[ 91., 168., 224., 215., 127.],
          [114., 211., 295., 262., 149.],
          [192., 259., 282., 214., 122.],
          [194., 251., 253., 169.,  86.],
          [ 96., 112., 110.,  68.,  31.]]]],
       grad_fn=<MkldnnConvolutionBackward>)


## Stride：步长
![EXRwI6](https://gitee.com/pxqp9W/testmarkdown/raw/master/imgs/2020/07/EXRwI6.png)
- 卷积过程中，有时需要通过padding来避免信息损失，有时也要在卷积时通过设置的步长（Stride）来压缩一部分信息，或者使输出的尺寸小于输入的尺寸。

In [5]:
input = [3,4,6,5,7, 2,4,6,8,2, 1,6,7,8,4, 9,7,4,6,2, 3,7,5,4,1]
input = torch.Tensor(input).view(1, 1, 5, 5) # input -> (B,C,W,H)形状的tensor
conv_layer = torch.nn.Conv2d(1, 1, kernel_size=3, stride=2, bias=False) # 设置步长为2
#  # (m:output chanels, n:input chanels, kernel_width, kernel_height)
kernel = torch.Tensor([1,2,3,4,5,6,7,8,9]).view(1, 1, 3, 3)  # -> (output Channel, input Channel, weight, height)
conv_layer.weight.data = kernel.data # 将kernel作为卷积层的权重
output = conv_layer(input) 
print(output)

tensor([[[[211., 262.],
          [251., 169.]]]], grad_fn=<MkldnnConvolutionBackward>)


## Subsampling：Max Pooling
![Sw3MGX](https://gitee.com/pxqp9W/testmarkdown/raw/master/imgs/2020/07/Sw3MGX.png)
- 缩小图像（或称为下采样（subsampled）或降采样（downsampled））的主要目的
- [CNN中Max Pooling的作用_XingLiu's Blog-CSDN博客_max-pooling](https://blog.csdn.net/pangjiuzala/article/details/71840947)

In [6]:
input = [3,4,6,5,
         2,4,6,8,
         1,6,7,8,
         9,7,4,6, ]
input = torch.Tensor(input).view(1, 1, 4, 4)
maxpooling_layer = torch.nn.MaxPool2d(kernel_size=2) # 默认stride = 2
output = maxpooling_layer(input)
print(output)

tensor([[[[4., 8.],
          [9., 8.]]]])


## A Simple Convolutional Neural Network
